In [ ]:
pip list

Package                   Version
------------------------- -----------
altair                    5.5.0
anyio                     4.11.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.4.0
babel                     2.17.0
beautifulsoup4            4.14.2
bleach                    6.3.0
blinker                   1.9.0
cachetools                6.2.2
certifi                   2025.11.12
cffi                      2.0.0
charset-normalizer        3.4.4
click                     8.3.0
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.17
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fonttools                 4.60.1
fqdn                      1.5.1
gitdb                     4.0.12
GitPython                 3.1.45
greenlet                  3.2.4
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.1.0
ipython                   9.7.0
ipython_pygments_lexers   1.1.1
ipywidgets                8.1.8
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
json5                     0.12.1
jsonpointer               3.0.0
jsonschema                4.25.1
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_client            8.6.3
jupyter-console           6.6.3
jupyter_core              5.9.1
jupyter-events            0.12.0
jupyter-lsp               2.3.0
jupyter_server            2.17.0
jupyter_server_terminals  0.5.3
jupyterlab                4.4.10
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.16
kiwisolver                1.4.9
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib                3.10.7
matplotlib-inline         0.2.1
mistune                   3.1.4
mysql-connector           2.2.9
mysql-connector-python    9.5.0
narwhals                  2.11.0
nbclient                  0.10.2
nbconvert                 7.16.6
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.4.7
notebook_shim             0.2.4
numpy                     2.3.4
packaging                 25.0
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.5
patsy                     1.0.2
pillow                    12.0.0
pip                       25.2
platformdirs              4.5.0
plotly                    6.5.0
plotly-express            0.4.1
prometheus_client         0.23.1
prompt_toolkit            3.0.52
protobuf                  6.33.1
psutil                    7.1.3
pure_eval                 0.2.3
pyarrow                   21.0.0
pycparser                 2.23
pydeck                    0.9.1
Pygments                  2.19.2
pyodbc                    5.3.0
pyparsing                 3.2.5
python-dateutil           2.9.0.post0
python-json-logger        4.0.0
pytz                      2025.2
pywinpty                  3.0.2
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.32.5
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.28.0
scipy                     1.16.3
seaborn                   0.13.2
Send2Trash                1.8.3
setuptools                80.9.0
six                       1.17.0
smmap                     5.0.2
sniffio                   1.3.1
soupsieve                 2.8
SQLAlchemy                2.0.44
stack-data                0.6.3
statsmodels               0.14.5
streamlit                 1.51.0
streamlit-charts          0.1.1
streamlit-plotly-events   0.0.6
tenacity                  9.1.2
terminado                 0.18.1
tinycss2                  1.4.0
toml                      0.10.2
tornado                   6.5.2
traitlets                 5.14.3
typing_extensions         4.15.0
tzdata                    2025.2
uri-template              1.3.0
urllib3                   2.5.0
watchdog                  6.0.0
wcwidth                   0.2.14
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
widgetsnbextension        4.0.15
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import pandas as pd
import json
import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ag_data_path =r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/transaction/country/india/state/'
ag_file_path= [os.path.join(root, filename) for root, dirs, files in os.walk(ag_data_path) for filename in files if filename.endswith('.json')] 
agg_state_list=os.listdir(ag_data_path)

ag_trans_clm={'State':[], 'Year':[],'Quarter':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in agg_state_list:
    p_i=ag_data_path+i+"/"
    agg_yr=os.listdir(p_i)
    for j in agg_yr:
        p_j=p_i+j+"/"
        agg_yr_list=os.listdir(p_j)
        for k in agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              ag_trans_clm['Transaction_type'].append(Name)
              ag_trans_clm['Transaction_count'].append(count)
              ag_trans_clm['Transaction_amount'].append(amount)
              ag_trans_clm['State'].append(i)
              ag_trans_clm['Year'].append(j)
              ag_trans_clm['Quarter'].append(int(k.strip('.json')))
#Succesfully created a dataframe
agg_Trans=pd.DataFrame(ag_trans_clm)

In [ ]:
agg_Trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [3]:
import pyodbc

In [4]:
import pyodbc

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)

cursor = conn.cursor()
print("Connected successfully!")

Connected successfully!

In [5]:
# 1) Inspect your DataFrame
print(agg_Trans.shape)
print(agg_Trans.columns.tolist())       # EXACT column names (case sensitive for attribute access)
print(agg_Trans.head())

# 2) Make sure columns match the SQL table columns
# expected: ['year','quarter','state','transaction_type','transaction_count','transaction_amount']

(5034, 6)
['State', 'Year', 'Quarter', 'Transaction_type', 'Transaction_count', 'Transaction_amount']
                       State  Year  Quarter          Transaction_type  \
0  andaman-&-nicobar-islands  2018        1  Recharge & bill payments
1  andaman-&-nicobar-islands  2018        1     Peer-to-peer payments
2  andaman-&-nicobar-islands  2018        1         Merchant payments
3  andaman-&-nicobar-islands  2018        1        Financial Services
4  andaman-&-nicobar-islands  2018        1                    Others

   Transaction_count  Transaction_amount
0               4200        1.845307e+06
1               1871        1.213866e+07
2                298        4.525072e+05
3                 33        1.060142e+04
4                256        1.846899e+05

In [6]:
import pyodbc
import pandas as pd
import numpy as np

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)
cursor = conn.cursor()

insert_sql = """
INSERT INTO dbo.aggregated_transaction
(Year, Quarter, State, Transaction_type, Transaction_count, Transaction_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data_iter = [
    (int(r.Year), int(r.Quarter), r.State, r.Transaction_type, int(r.Transaction_count), float(r.Transaction_amount))
    for r in agg_Trans.itertuples(index=False)
]

cursor.fast_executemany = True   # speeds up executemany
cursor.executemany(insert_sql, data_iter)
conn.commit()

print("Inserted", cursor.rowcount, "rows (last batch rowcount).")

cursor.close()
conn.close()

Inserted -1 rows (last batch rowcount).

In [7]:
ag_ins_datapath=r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/insurance/country/india/state/'
ag_ins_state_list=os.listdir(ag_ins_datapath)

ag_ins_clm={'State':[], 'Year':[],'Quarter':[],'insurance_type':[], 'insurance_count':[], 'insurance_amount':[]}

for i in ag_ins_state_list:
    p_i=ag_ins_datapath+i+"/"
    ag_ins_yr=os.listdir(p_i)
    for j in ag_ins_yr:
        p_j=p_i+j+"/"
        ag_ins_yr_list=os.listdir(p_j)
        for k in ag_ins_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              ag_ins_clm['insurance_type'].append(Name)
              ag_ins_clm['insurance_count'].append(count)
              ag_ins_clm['insurance_amount'].append(amount)
              ag_ins_clm['State'].append(i)
              ag_ins_clm['Year'].append(j)
              ag_ins_clm['Quarter'].append(int(k.strip('.json')))
#Succesfully created a dataframe
agg_ins=pd.DataFrame(ag_ins_clm)

In [8]:
import pyodbc
import pandas as pd
import numpy as np

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)
cursor = conn.cursor()

insert_sql = """
INSERT INTO dbo.aggregated_insurance
(Year, Quarter, State, insurance_type, insurance_count, insurance_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data_iter = [
    (int(r.Year), int(r.Quarter), r.State, r.insurance_type, int(r.insurance_count), float(r.insurance_amount))
    for r in agg_ins.itertuples(index=False)
]

cursor.fast_executemany = True   # speeds up executemany
cursor.executemany(insert_sql, data_iter)
conn.commit()

print("Inserted", cursor.rowcount, "rows (last batch rowcount).")

cursor.close()
conn.close()

Inserted -1 rows (last batch rowcount).

In [9]:
agg_ins.tail()

,State,Year,Quarter,insurance_type,insurance_count,insurance_amount
677,west-bengal,2023,4,Insurance,72712,100365562.0
678,west-bengal,2024,1,Insurance,79576,104987909.0
679,west-bengal,2024,2,Insurance,67048,89476633.0
680,west-bengal,2024,3,Insurance,77158,107451766.0
681,west-bengal,2024,4,Insurance,91719,120602777.0

In [10]:
import os
import pandas as pd
user_datapath=r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/'
ag_user=os.listdir(user_datapath)

ag_user_clm={'State':[], 'Year':[],'Quarter':[],'user_brand':[], 'user_count':[], 'user_percentage':[]}

for i in ag_user:
    p_i=user_datapath+i+"/"
    ag_user_yr=os.listdir(p_i)
    for j in ag_user_yr:
        p_j=p_i+j+"/"
        ag_user_yr_list=os.listdir(p_j)
        for k in ag_user_yr_list:
            p_k=p_j+k
            print(p_k)
            Data=open(p_k,'r')
            D=json.load(Data)
            print(D)
            
            users_by_device = D['data'].get('usersByDevice')
            if not users_by_device:
                continue
            for device in users_by_device:
               
                brand = device.get('brand') or device.get('Brand') or 'Unknown'
                count = device.get('count', device.get('Users_Count', 0)) 
                percentage = device.get('percentage', 0.0) 
                ag_user_clm['user_brand'].append(brand)
                ag_user_clm['user_count'].append(count)
                ag_user_clm['user_percentage'].append(percentage)
                ag_user_clm['State'].append(i)
                ag_user_clm['Year'].append(j)
                ag_user_clm['Quarter'].append(int(k.strip('.json')))
#Succesfully created a dataframe
agg_user=pd.DataFrame(ag_user_clm)

C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2018/1.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 6740, 'appOpens': 0}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 1665, 'percentage': 0.2470326409495549}, {'brand': 'Samsung', 'count': 1445, 'percentage': 0.21439169139465875}, {'brand': 'Vivo', 'count': 982, 'percentage': 0.1456973293768546}, {'brand': 'Oppo', 'count': 501, 'percentage': 0.07433234421364986}, {'brand': 'OnePlus', 'count': 332, 'percentage': 0.04925816023738872}, {'brand': 'Realme', 'count': 316, 'percentage': 0.04688427299703264}, {'brand': 'Apple', 'count': 229, 'percentage': 0.03397626112759644}, {'brand': 'Motorola', 'count': 226, 'percentage': 0.03353115727002967}, {'brand': 'Lenovo', 'count': 202, 'percentage': 0.02997032640949555}, {'brand': 'Huawei', 'count': 158, 'percentage': 0.02344213649851632}, {'brand': 'Others', 'count': 684, 'percentage': 0.10148367952522255}]}, 'responseTimestamp': 1630501494543}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2018/2.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 9405, 'appOpens': 0}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 2303, 'percentage': 0.24486975013290802}, {'brand': 'Samsung', 'count': 1923, 'percentage': 0.20446570972886763}, {'brand': 'Vivo', 'count': 1523, 'percentage': 0.1619351408825093}, {'brand': 'Oppo', 'count': 708, 'percentage': 0.07527910685805422}, {'brand': 'OnePlus', 'count': 466, 'percentage': 0.049548112706007445}, {'brand': 'Realme', 'count': 465, 'percentage': 0.049441786283891544}, {'brand': 'Motorola', 'count': 319, 'percentage': 0.03391812865497076}, {'brand': 'Apple', 'count': 308, 'percentage': 0.03274853801169591}, {'brand': 'Lenovo', 'count': 244, 'percentage': 0.025943646996278574}, {'brand': 'Huawei', 'count': 230, 'percentage': 0.024455077086656035}, {'brand': 'Others', 'count': 916, 'percentage': 0.09739500265816055}]}, 'responseTimestamp': 1630501494939}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2018/3.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 12149, 'appOpens': 0}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 2950, 'percentage': 0.24281833895793892}, {'brand': 'Samsung', 'count': 2409, 'percentage': 0.19828792493209318}, {'brand': 'Vivo', 'count': 2063, 'percentage': 0.1698082146678739}, {'brand': 'Oppo', 'count': 988, 'percentage': 0.08132356572557412}, {'brand': 'OnePlus', 'count': 617, 'percentage': 0.05078607292781299}, {'brand': 'Realme', 'count': 603, 'percentage': 0.04963371470902955}, {'brand': 'Motorola', 'count': 390, 'percentage': 0.03210140752325294}, {'brand': 'Apple', 'count': 371, 'percentage': 0.03053749279776113}, {'brand': 'Huawei', 'count': 314, 'percentage': 0.0258457486212857}, {'brand': 'Lenovo', 'count': 299, 'percentage': 0.024611079101160588}, {'brand': 'Others', 'count': 1145, 'percentage': 0.09424644003621697}]}, 'responseTimestamp': 1630501495385}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2018/4.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 15222, 'appOpens': 0}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 3719, 'percentage': 0.24431743529102615}, {'brand': 'Samsung', 'count': 2936, 'percentage': 0.19287872815661541}, {'brand': 'Vivo', 'count': 2742, 'percentage': 0.1801340165549862}, {'brand': 'Oppo', 'count': 1268, 'percentage': 0.08330048613848377}, {'brand': 'Realme', 'count': 760, 'percentage': 0.04992773617133097}, {'brand': 'OnePlus', 'count': 721, 'percentage': 0.0473656549730653}, {'brand': 'Motorola', 'count': 474, 'percentage': 0.031139140717382736}, {'brand': 'Apple', 'count': 455, 'percentage': 0.02989094731309946}, {'brand': 'Huawei', 'count': 398, 'percentage': 0.02614636710024964}, {'brand': 'Lenovo', 'count': 377, 'percentage': 0.024766784916568124}, {'brand': 'Others', 'count': 1372, 'percentage': 0.09013270266719223}]}, 'responseTimestamp': 1630501495714}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2019/1.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 18596, 'appOpens': 0}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 4576, 'percentage': 0.24607442460744247}, {'brand': 'Samsung', 'count': 3567, 'percentage': 0.19181544418154442}, {'brand': 'Vivo', 'count': 3420, 'percentage': 0.18391051839105185}, {'brand': 'Oppo', 'count': 1600, 'percentage': 0.08604000860400086}, {'brand': 'Realme', 'count': 897, 'percentage': 0.04823617982361798}, {'brand': 'OnePlus', 'count': 855, 'percentage': 0.04597762959776296}, {'brand': 'Motorola', 'count': 561, 'percentage': 0.0301677780167778}, {'brand': 'Apple', 'count': 515, 'percentage': 0.027694127769412775}, {'brand': 'Huawei', 'count': 515, 'percentage': 0.027694127769412775}, {'brand': 'Lenovo', 'count': 426, 'percentage': 0.02290815229081523}, {'brand': 'Others', 'count': 1664, 'percentage': 0.0894816089481609}]}, 'responseTimestamp': 1630501496432}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2019/2.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 21731, 'appOpens': 52640}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 5296, 'percentage': 0.24370714647278083}, {'brand': 'Samsung', 'count': 4165, 'percentage': 0.19166168146886936}, {'brand': 'Vivo', 'count': 4102, 'percentage': 0.18876259721135705}, {'brand': 'Oppo', 'count': 1905, 'percentage': 0.08766278588191984}, {'brand': 'Realme', 'count': 1012, 'percentage': 0.04656941696194377}, {'brand': 'OnePlus', 'count': 950, 'percentage': 0.04371634991486816}, {'brand': 'Huawei', 'count': 644, 'percentage': 0.029635083521236942}, {'brand': 'Motorola', 'count': 630, 'percentage': 0.028990842575123098}, {'brand': 'Apple', 'count': 569, 'percentage': 0.026183792738484195}, {'brand': 'Lenovo', 'count': 477, 'percentage': 0.021950209378307488}, {'brand': 'Others', 'count': 1981, 'percentage': 0.09116009387510929}]}, 'responseTimestamp': 1630501496746}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2019/3.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 23931, 'appOpens': 171107}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 5819, 'percentage': 0.24315741088964105}, {'brand': 'Vivo', 'count': 4685, 'percentage': 0.19577117546278885}, {'brand': 'Samsung', 'count': 4508, 'percentage': 0.1883749112030421}, {'brand': 'Oppo', 'count': 2108, 'percentage': 0.08808658225732313}, {'brand': 'Realme', 'count': 1158, 'percentage': 0.04838911871630939}, {'brand': 'OnePlus', 'count': 1045, 'percentage': 0.04366720989511512}, {'brand': 'Huawei', 'count': 725, 'percentage': 0.030295432702352597}, {'brand': 'Motorola', 'count': 660, 'percentage': 0.02757929046007271}, {'brand': 'Apple', 'count': 630, 'percentage': 0.026325686348251224}, {'brand': 'Lenovo', 'count': 483, 'percentage': 0.020183026200325936}, {'brand': 'Others', 'count': 2110, 'percentage': 0.0881701558647779}]}, 'responseTimestamp': 1630501497383}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2019/4.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 25960, 'appOpens': 177012}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 6259, 'percentage': 0.24110169491525424}, {'brand': 'Vivo', 'count': 5190, 'percentage': 0.19992295839753466}, {'brand': 'Samsung', 'count': 4900, 'percentage': 0.18875192604006163}, {'brand': 'Oppo', 'count': 2329, 'percentage': 0.08971494607087828}, {'brand': 'Realme', 'count': 1329, 'percentage': 0.051194144838212635}, {'brand': 'OnePlus', 'count': 1124, 'percentage': 0.04329738058551618}, {'brand': 'Huawei', 'count': 798, 'percentage': 0.03073959938366718}, {'brand': 'Motorola', 'count': 682, 'percentage': 0.026271186440677965}, {'brand': 'Apple', 'count': 678, 'percentage': 0.026117103235747303}, {'brand': 'Lenovo', 'count': 488, 'percentage': 0.018798151001540832}, {'brand': 'Others', 'count': 2183, 'percentage': 0.08409090909090909}]}, 'responseTimestamp': 1630501497840}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2020/1.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 28368, 'appOpens': 193586}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 6803, 'percentage': 0.23981246474901297}, {'brand': 'Vivo', 'count': 5880, 'percentage': 0.20727580372250423}, {'brand': 'Samsung', 'count': 5335, 'percentage': 0.1880640157924422}, {'brand': 'Oppo', 'count': 2557, 'percentage': 0.09013677382966723}, {'brand': 'Realme', 'count': 1511, 'percentage': 0.05326424139875917}, {'brand': 'OnePlus', 'count': 1184, 'percentage': 0.04173716864072194}, {'brand': 'Huawei', 'count': 891, 'percentage': 0.03140862944162436}, {'brand': 'Apple', 'count': 735, 'percentage': 0.02590947546531303}, {'brand': 'Motorola', 'count': 715, 'percentage': 0.025204455724760294}, {'brand': 'Lenovo', 'count': 500, 'percentage': 0.017625493513818386}, {'brand': 'Others', 'count': 2257, 'percentage': 0.0795614777213762}]}, 'responseTimestamp': 1630501498181}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2020/2.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 32710, 'appOpens': 305072}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 7805, 'percentage': 0.2386120452461021}, {'brand': 'Vivo', 'count': 7122, 'percentage': 0.21773158055640476}, {'brand': 'Samsung', 'count': 6030, 'percentage': 0.1843472944053806}, {'brand': 'Oppo', 'count': 2976, 'percentage': 0.09098135126872516}, {'brand': 'Realme', 'count': 1761, 'percentage': 0.053836747172118615}, {'brand': 'OnePlus', 'count': 1271, 'percentage': 0.03885661877101804}, {'brand': 'Huawei', 'count': 1005, 'percentage': 0.030724549067563438}, {'brand': 'Apple', 'count': 792, 'percentage': 0.024212778966676857}, {'brand': 'Motorola', 'count': 779, 'percentage': 0.023815346988688476}, {'brand': 'Lenovo', 'count': 552, 'percentage': 0.01687557321919902}, {'brand': 'Others', 'count': 2617, 'percentage': 0.0800061143381229}]}, 'responseTimestamp': 1630501498565}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2020/3.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 41335, 'appOpens': 515565}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 9794, 'percentage': 0.2369420587879521}, {'brand': 'Vivo', 'count': 9556, 'percentage': 0.23118422644248215}, {'brand': 'Samsung', 'count': 7572, 'percentage': 0.18318616184831257}, {'brand': 'Oppo', 'count': 3730, 'percentage': 0.09023829684286924}, {'brand': 'Realme', 'count': 2285, 'percentage': 0.05528002903108745}, {'brand': 'OnePlus', 'count': 1440, 'percentage': 0.03483730494738115}, {'brand': 'Huawei', 'count': 1213, 'percentage': 0.029345590903592598}, {'brand': 'Motorola', 'count': 907, 'percentage': 0.021942663602274103}, {'brand': 'Apple', 'count': 870, 'percentage': 0.021047538405709446}, {'brand': 'Lenovo', 'count': 606, 'percentage': 0.014660699165356235}, {'brand': 'Others', 'count': 3362, 'percentage': 0.08133543002298295}]}, 'responseTimestamp': 1630501498900}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2020/4.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 52396, 'appOpens': 887208}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 12398, 'percentage': 0.23662111611573403}, {'brand': 'Vivo', 'count': 12275, 'percentage': 0.23427360867241775}, {'brand': 'Samsung', 'count': 9938, 'percentage': 0.18967096724940835}, {'brand': 'Oppo', 'count': 4723, 'percentage': 0.0901404687380716}, {'brand': 'Realme', 'count': 2996, 'percentage': 0.05717993739980151}, {'brand': 'OnePlus', 'count': 1638, 'percentage': 0.031261928391480266}, {'brand': 'Huawei', 'count': 1472, 'percentage': 0.028093747614321703}, {'brand': 'Motorola', 'count': 1032, 'percentage': 0.019696160012214674}, {'brand': 'Apple', 'count': 973, 'percentage': 0.018570119856477593}, {'brand': 'Lenovo', 'count': 708, 'percentage': 0.01351248186884495}, {'brand': 'Others', 'count': 4243, 'percentage': 0.08097946408122758}]}, 'responseTimestamp': 1630501499406}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2021/1.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 57758, 'appOpens': 1004336}, 'usersByDevice': [{'brand': 'Vivo', 'count': 13812, 'percentage': 0.23913570414488036}, {'brand': 'Xiaomi', 'count': 13714, 'percentage': 0.2374389694934035}, {'brand': 'Samsung', 'count': 10861, 'percentage': 0.18804321479275599}, {'brand': 'Oppo', 'count': 5158, 'percentage': 0.08930364624813879}, {'brand': 'Realme', 'count': 3419, 'percentage': 0.05919526299387098}, {'brand': 'OnePlus', 'count': 1773, 'percentage': 0.030697046296616917}, {'brand': 'Huawei', 'count': 1575, 'percentage': 0.027268949755877972}, {'brand': 'Motorola', 'count': 1062, 'percentage': 0.018387063263963433}, {'brand': 'Apple', 'count': 1056, 'percentage': 0.018283181550607708}, {'brand': 'Tecno', 'count': 796, 'percentage': 0.013781640638526264}, {'brand': 'Others', 'count': 4532, 'percentage': 0.07846532082135808}]}, 'responseTimestamp': 1630501499750}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2021/2.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 62095, 'appOpens': 2248223}, 'usersByDevice': [{'brand': 'Vivo', 'count': 15056, 'percentage': 0.2424671873741847}, {'brand': 'Xiaomi', 'count': 14788, 'percentage': 0.2381512199049843}, {'brand': 'Samsung', 'count': 11476, 'percentage': 0.18481359207665674}, {'brand': 'Oppo', 'count': 5456, 'percentage': 0.0878653675819309}, {'brand': 'Realme', 'count': 4034, 'percentage': 0.06496497302520332}, {'brand': 'OnePlus', 'count': 1981, 'percentage': 0.031902729688380704}, {'brand': 'Huawei', 'count': 1559, 'percentage': 0.025106691360012885}, {'brand': 'Apple', 'count': 1153, 'percentage': 0.018568322731298815}, {'brand': 'Motorola', 'count': 1054, 'percentage': 0.0169739914646912}, {'brand': 'Tecno', 'count': 974, 'percentage': 0.015685642966422417}, {'brand': 'Others', 'count': 4564, 'percentage': 0.073500281826234}]}, 'responseTimestamp': 1630501500085}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2021/3.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 66982, 'appOpens': 3121625}, 'usersByDevice': [{'brand': 'Vivo', 'count': 16411, 'percentage': 0.24500612104744557}, {'brand': 'Xiaomi', 'count': 15938, 'percentage': 0.2379445224090054}, {'brand': 'Samsung', 'count': 12028, 'percentage': 0.17957063091576841}, {'brand': 'Oppo', 'count': 5853, 'percentage': 0.0873816846316921}, {'brand': 'Realme', 'count': 4808, 'percentage': 0.0717804783374638}, {'brand': 'OnePlus', 'count': 2306, 'percentage': 0.03442715953539757}, {'brand': 'Huawei', 'count': 1567, 'percentage': 0.023394344749335643}, {'brand': 'Apple', 'count': 1283, 'percentage': 0.01915439968946881}, {'brand': 'Tecno', 'count': 1178, 'percentage': 0.017586814368039175}, {'brand': 'Motorola', 'count': 1017, 'percentage': 0.015183183541847063}, {'brand': 'Others', 'count': 4593, 'percentage': 0.06857066077453644}]}, 'responseTimestamp': 1634575136755}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2021/4.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 71780, 'appOpens': 2112910}, 'usersByDevice': [{'brand': 'Vivo', 'count': 17597, 'percentage': 0.24515185288381164}, {'brand': 'Xiaomi', 'count': 16968, 'percentage': 0.2363889662858735}, {'brand': 'Samsung', 'count': 12574, 'percentage': 0.17517414321538033}, {'brand': 'Oppo', 'count': 6127, 'percentage': 0.08535803845082196}, {'brand': 'Realme', 'count': 5830, 'percentage': 0.08122039565338535}, {'brand': 'OnePlus', 'count': 2691, 'percentage': 0.03748955140707718}, {'brand': 'Apple', 'count': 1490, 'percentage': 0.020757871273335192}, {'brand': 'Huawei', 'count': 1459, 'percentage': 0.020325996099191977}, {'brand': 'Tecno', 'count': 1417, 'percentage': 0.01974087489551407}, {'brand': 'Motorola', 'count': 1055, 'percentage': 0.014697687378099749}, {'brand': 'Others', 'count': 4572, 'percentage': 0.06369462245750905}]}, 'responseTimestamp': 1643295751539}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2022/1.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 76288, 'appOpens': 3847407}, 'usersByDevice': [{'brand': 'Vivo', 'count': 18688, 'percentage': 0.24496644295302014}, {'brand': 'Xiaomi', 'count': 17957, 'percentage': 0.23538433305369127}, {'brand': 'Samsung', 'count': 12955, 'percentage': 0.16981700922818793}, {'brand': 'Realme', 'count': 6769, 'percentage': 0.08872955117449664}, {'brand': 'Oppo', 'count': 6461, 'percentage': 0.08469221895973154}, {'brand': 'OnePlus', 'count': 3005, 'percentage': 0.039390205536912755}, {'brand': 'Tecno', 'count': 1770, 'percentage': 0.02320155201342282}, {'brand': 'Apple', 'count': 1634, 'percentage': 0.02141883389261745}, {'brand': 'Huawei', 'count': 1441, 'percentage': 0.018888947147651006}, {'brand': 'Motorola', 'count': 1050, 'percentage': 0.01376363255033557}, {'brand': 'Others', 'count': 4558, 'percentage': 0.05974727348993288}]}, 'responseTimestamp': 1651127651906}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2022/2.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 80530, 'appOpens': 5180013}, 'usersByDevice': None}, 'responseTimestamp': 1669732284426}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2022/3.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 84642, 'appOpens': 6068354}, 'usersByDevice': None}, 'responseTimestamp': 1669732415940}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2022/4.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 88442, 'appOpens': 4354093}, 'usersByDevice': None}, 'responseTimestamp': 1674558294583}
C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/aggregated/user/country/india/state/andaman-&-nicobar-islands/2023/1.json

KeyboardInterrupt:

In [ ]:
agg_user

,State,Year,Quarter,user_brand,user_count,user_percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,west-bengal,2022,1,Lenovo,330017,0.015056
6728,west-bengal,2022,1,Infinix,284678,0.012987
6729,west-bengal,2022,1,Asus,280347,0.012790
6730,west-bengal,2022,1,Apple,277752,0.012671
6731,west-bengal,2022,1,Others,2196334,0.100199

In [ ]:
conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)
cursor = conn.cursor()

In [ ]:
import pyodbc
import pandas as pd
import numpy as np

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)
cursor = conn.cursor()

insert_sql = """
INSERT INTO aggregated_user
(Year, Quarter, State, user_brand, user_count, user_percentage)
VALUES (?, ?, ?, ?, ?, ?)
"""

data_iter = [
    (int(r.Year), int(r.Quarter), r.State, r.user_brand, int(r.user_count), float(r.user_percentage))
    for r in agg_user.itertuples(index=False)
]

cursor.fast_executemany = True   # speeds up executemany
cursor.executemany(insert_sql,data_iter)
conn.commit()

print("Inserted", cursor.rowcount, "rows (last batch rowcount).")

cursor.close()
conn.close()

Inserted -1 rows (last batch rowcount).

In [ ]:
agg_user

,State,Year,Quarter,user_brand,user_count,user_percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,west-bengal,2022,1,Lenovo,330017,0.015056
6728,west-bengal,2022,1,Infinix,284678,0.012987
6729,west-bengal,2022,1,Asus,280347,0.012790
6730,west-bengal,2022,1,Apple,277752,0.012671
6731,west-bengal,2022,1,Others,2196334,0.100199

In [11]:
m_trans_datapath=r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/map/transaction//hover/country/india/state/'
m_trans_state_list=os.listdir(m_trans_datapath)

m_trans_clm={'State':[], 'Year':[],'Quarter':[],'m_transaction_type':[], 'm_transaction_count':[], 'm_transaction_amount':[]}

for i in m_trans_state_list:
    p_i=m_trans_datapath+i+"/"
    m_yr=os.listdir(p_i)
    for j in m_yr:
        p_j=p_i+j+"/"
        m_yr_list=os.listdir(p_j)
        for k in m_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              m_trans_clm['m_transaction_type'].append(Name)
              m_trans_clm['m_transaction_count'].append(count)
              m_trans_clm['m_transaction_amount'].append(amount)
              m_trans_clm['State'].append(i)
              m_trans_clm['Year'].append(j)
              m_trans_clm['Quarter'].append(int(k.strip('.json')))
#Succesfully created a dataframe
m_trans=pd.DataFrame(m_trans_clm)

In [ ]:
import pyodbc
import pandas as pd
import numpy as np

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)
cursor = conn.cursor()

insert_sql = """
INSERT INTO map_transaction
(Year, Quarter, State, m_transaction_type, m_transaction_count, m_transaction_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data_iter = [
    (int(r.Year), int(r.Quarter), r.State, r.m_transaction_type, int(r.m_transaction_count), float(r.m_transaction_amount))
    for r in m_trans.itertuples(index=False)
]

cursor.fast_executemany = True   # speeds up executemany
cursor.executemany(insert_sql,data_iter)
conn.commit()

print("Inserted", cursor.rowcount, "rows (last batch rowcount).")

cursor.close()
conn.close()

Inserted -1 rows (last batch rowcount).

In [ ]:
m_trans

,State,Year,Quarter,m_transaction_type,m_transaction_count,m_transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [12]:
m_user_datapath = r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/map/users/hover/country/india/state/'

In [14]:
import os
import json
import pandas as pd

# Define the path
m_user_datapath = r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/map/user/hover/country/india/state/'

m_clm_user = {'State': [],'Year': [], 'Quarter': [],'District': [],'m_registered_Users': [],'m_app_Opens': []}    
   

for state in os.listdir(m_user_datapath):
    state_path = os.path.join(m_user_datapath, state)
    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)
        for quarter_file in os.listdir(year_path):
            if quarter_file.endswith('.json'):
                file_path = os.path.join(year_path, quarter_file)  
                with open(file_path, 'r') as file:
                    json_data = json.load(file)
                quarter = int(quarter_file.replace('.json', ''))
                hover_data = json_data['data']['hoverData']
                for district, metrics in hover_data.items():
                    m_clm_user['State'].append(state)
                    m_clm_user['Year'].append(year)
                    m_clm_user['Quarter'].append(quarter)
                    m_clm_user['District'].append(district)
                    m_clm_user['m_registered_Users'].append(metrics['registeredUsers'])
                    m_clm_user['m_app_Opens'].append(metrics['appOpens'])

m_user = pd.DataFrame(m_clm_user)

In [15]:
import pyodbc
import pandas as pd
import numpy as np

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)
cursor = conn.cursor()

insert_sql = """
INSERT INTO map_user
(Year, Quarter, State, District, m_registered_Users, m_app_Opens)
VALUES (?, ?, ?, ?, ?, ?)
"""

data_iter = [
    (int(r.Year), int(r.Quarter), r.State, r.District, int(r.m_registered_Users), int(r.m_app_Opens))
    for r in m_user.itertuples(index=False)
]

cursor.fast_executemany = True   # speeds up executemany
cursor.executemany(insert_sql,data_iter)
conn.commit()

print("Inserted", cursor.rowcount, "rows (last batch rowcount).")

cursor.close()
conn.close()

Inserted -1 rows (last batch rowcount).

In [16]:
m_user

,State,Year,Quarter,District,m_registered_Users,m_app_Opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

In [17]:
m_ins_datapath=r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/map/insurance/hover/country/india/state/'
m_ins_state_list=os.listdir(m_ins_datapath)

m_ins_clm={'State':[], 'Year':[],'Quarter':[],'m_insurance_type':[], 'm_insurance_count':[], 'm_insurance_amount':[]}

for i in m_ins_state_list:
    p_i=m_ins_datapath+i+"/"
    m_ins_yr=os.listdir(p_i)
    for j in m_ins_yr:
        p_j=p_i+j+"/"
        m_ins_yr_list=os.listdir(p_j)
        for k in m_ins_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
                Name = z['name']
                count = z['metric'][0]['count']
                amount = z['metric'][0]['amount']
                m_ins_clm['m_insurance_type'].append(Name)
                m_ins_clm['m_insurance_count'].append(count)
                m_ins_clm['m_insurance_amount'].append(amount)
                m_ins_clm['State'].append(i)
                m_ins_clm['Year'].append(j)
                m_ins_clm['Quarter'].append(int(k.strip('.json')))
    
#Succesfully created a dataframe
m_ins=pd.DataFrame(m_ins_clm)

In [18]:
import pyodbc
import pandas as pd
import numpy as np

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=VIGNESH\SQLEXPRESS;"
    r"DATABASE=phonepe;"
    r"Trusted_Connection=yes;"
)
cursor = conn.cursor()

insert_sql = """
INSERT INTO map_insurance
(Year, Quarter, State, m_insurance_type, m_insurance_count, m_insurance_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data_iter = [
    (int(r.Year), int(r.Quarter), r.State, r.m_insurance_type, int(r.m_insurance_count), int(r.m_insurance_amount))
    for r in m_ins .itertuples(index=False)
]

cursor.fast_executemany = True   # speeds up executemany
cursor.executemany(insert_sql,data_iter)
conn.commit()

print("Inserted", cursor.rowcount, "rows (last batch rowcount).")

cursor.close()
conn.close()

Inserted -1 rows (last batch rowcount).

In [19]:
m_ins

,State,Year,Quarter,m_insurance_type,m_insurance_count,m_insurance_amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,west-bengal,2024,4,nadia district,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,3559,4439061.0

In [20]:

top_trans_path = r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/top/transaction/country/india/'

# Dictionaries to collect data
state_cols = {
    'Year': [],
    'Quarter': [],
    'State': [],
    'Metric_Type': [],
    'Transaction_Count': [],
    'Transaction_Amount': []
}

district_cols = {
    'Year': [],
    'Quarter': [],
    'District': [],
    'Metric_Type': [],
    'Transaction_Count': [],
    'Transaction_Amount': []
}

pincode_cols = {
    'Year': [],
    'Quarter': [],
    'Pincode': [],
    'Metric_Type': [],
    'Transaction_Count': [],
    'Transaction_Amount': []
}

# Loop through year folders
year_list = os.listdir(top_trans_path)

for year in year_list:
    year_path = os.path.join(top_trans_path, year)
    if not os.path.isdir(year_path):
        continue

    # Loop through quarter json files inside the year folder
    quarter_files = os.listdir(year_path)

    for q_file in quarter_files:
        if not q_file.endswith('.json'):
            continue

        q_path = os.path.join(year_path, q_file)
        quarter = int(q_file.strip('.json'))  # '1.json' -> 1

        with open(q_path, 'r', encoding='utf-8') as f:
            D = json.load(f)

        # -------------------- STATES --------------------
        states_list = D['data'].get('states')
        if states_list:
            for s in states_list:
                state_cols['Year'].append(year)
                state_cols['Quarter'].append(quarter)
                state_cols['State'].append(s['entityName'])
                state_cols['Metric_Type'].append(s['metric']['type'])
                state_cols['Transaction_Count'].append(s['metric']['count'])
                state_cols['Transaction_Amount'].append(s['metric']['amount'])

        # -------------------- DISTRICTS --------------------
        districts_list = D['data'].get('districts')
        if districts_list:
            for d in districts_list:
                district_cols['Year'].append(year)
                district_cols['Quarter'].append(quarter)
                district_cols['District'].append(d['entityName'])
                district_cols['Metric_Type'].append(d['metric']['type'])
                district_cols['Transaction_Count'].append(d['metric']['count'])
                district_cols['Transaction_Amount'].append(d['metric']['amount'])

        # -------------------- PINCODES --------------------
        pincodes_list = D['data'].get('pincodes')
        if pincodes_list:
            for p in pincodes_list:
                pincode_cols['Year'].append(year)
                pincode_cols['Quarter'].append(quarter)
                pincode_cols['Pincode'].append(p['entityName'])
                pincode_cols['Metric_Type'].append(p['metric']['type'])
                pincode_cols['Transaction_Count'].append(p['metric']['count'])
                pincode_cols['Transaction_Amount'].append(p['metric']['amount'])

# Create DataFrames
top_trans_state_df = pd.DataFrame(state_cols)
top_trans_district_df = pd.DataFrame(district_cols)
top_trans_pincode_df = pd.DataFrame(pincode_cols)

In [21]:
import pyodbc
import pandas as pd

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=VIGNESH\\SQLEXPRESS;"
    "DATABASE=phonepe;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()
print("Connected to SQL Server!")

from sqlalchemy import create_engine

conn_str = (
    "mssql+pyodbc://VIGNESH\\SQLEXPRESS/phonepe?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

engine = create_engine(conn_str)

top_trans_state_df.to_sql(
    name="top_state_transaction",
    con=engine,
    if_exists="append",
    index=False
)
print("State data inserted!")

top_trans_district_df.to_sql(
    name="top_district_transaction",
    con=engine,
    if_exists="append",
    index=False
)
print("District data inserted!")

top_trans_pincode_df.to_sql(
    name="top_pincode_transaction",
    con=engine,
    if_exists="append",
    index=False
)
print("pincode data inserted!")

Connected to SQL Server!
State data inserted!
District data inserted!
pincode data inserted!

In [23]:
import os
import json
import pandas as pd

top_user_path = r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/top/user/country/india/'

# Dictionaries to collect data
state_cols = {
    'Year': [],
    'Quarter': [],
    'State': [],
    'registeredUsers': []
}

district_cols = {
    'Year': [],
    'Quarter': [],
    'District': [],
    'registeredUsers': []
}

pincode_cols = {
    'Year': [],
    'Quarter': [],
    'Pincode': [],
    'registeredUsers': []
}

# Loop through year folders
year_list = os.listdir(top_user_path)

for year in year_list:
    year_path = os.path.join(top_user_path, year)
    if not os.path.isdir(year_path):
        continue

    # Loop through quarter json files inside the year folder
    quarter_files = os.listdir(year_path)

    for q_file in quarter_files:
        if not q_file.endswith('.json'):
            continue

        q_path = os.path.join(year_path, q_file)
        quarter = int(q_file.replace('.json', ''))

        with open(q_path, 'r', encoding='utf-8') as f:
            D = json.load(f)

        # -------------------- STATES --------------------
        states_list = D['data'].get('states', [])
        for s in states_list:
            state_cols['Year'].append(int(year))
            state_cols['Quarter'].append(quarter)
            state_cols['State'].append(s["name"])
            state_cols['registeredUsers'].append(s["registeredUsers"])

        # -------------------- DISTRICTS --------------------
        districts_list = D['data'].get('districts', [])
        for d in districts_list:
            district_cols['Year'].append(int(year))
            district_cols['Quarter'].append(quarter)
            district_cols['District'].append(d["name"])
            district_cols['registeredUsers'].append(d["registeredUsers"])

        # -------------------- PINCODES --------------------
        pincodes_list = D['data'].get('pincodes', [])
        for p in pincodes_list:
            pincode_cols['Year'].append(int(year))
            pincode_cols['Quarter'].append(quarter)
            pincode_cols['Pincode'].append(p["name"])
            pincode_cols['registeredUsers'].append(p["registeredUsers"])

# Create DataFrames
top_user_state_df = pd.DataFrame(state_cols)
top_user_district_df = pd.DataFrame(district_cols)
top_user_pincode_df = pd.DataFrame(pincode_cols)

print(top_user_state_df.head())
print(top_user_district_df.head())
print(top_user_pincode_df.head())

   Year  Quarter           State  registeredUsers
0  2018        1     maharashtra          6106994
1  2018        1   uttar pradesh          4694250
2  2018        1       karnataka          3717763
3  2018        1  andhra pradesh          3336450
4  2018        1       telangana          3315560
   Year  Quarter         District  registeredUsers
0  2018        1  bengaluru urban          1922368
1  2018        1             pune          1211643
2  2018        1           jaipur           900773
3  2018        1  mumbai suburban           719300
4  2018        1        hyderabad           655175
   Year  Quarter Pincode  registeredUsers
0  2018        1  201301           114625
1  2018        1  500072           105012
2  2018        1  560068            98487
3  2018        1  110059            95496
4  2018        1  110092            83600

In [24]:
import sqlalchemy as sa
import pyodbc
import pandas as pd

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=VIGNESH\\SQLEXPRESS;"
    "DATABASE=phonepe;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()
print("Connected to SQL Server!")
# Connection string for MSSQL
conn_str = (
    "mssql+pyodbc://VIGNESH\\SQLEXPRESS/phonepe?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

engine = create_engine(conn_str)

# Insert state dataframe
top_user_state_df.to_sql(
    "top_user_state",
    con=engine,
    if_exists="append",
    index=False
)

# Insert district dataframe
top_user_district_df.to_sql(
    "top_user_district",
    con=engine,
    if_exists="append",
    index=False
)

# Insert pincode dataframe
top_user_pincode_df.to_sql(
    "top_user_pincode",
    con=engine,
    if_exists="append",
    index=False
)

print("All 3 dataframes inserted successfully!")

Connected to SQL Server!

All 3 dataframes inserted successfully!

In [26]:

top_ins__path = r'C:/Users/VICKY/Desktop/Guvi/projects/Project 1/new project/phonepe_dataanalysis/data/top/insurance/country/india/'

# Dictionaries to collect data
top_ins_state_cols = {
    'Year': [],
    'Quarter': [],
    'State': [],
    'Metric_Type': [],
    'Transaction_Count': [],
    'Transaction_Amount': []
}

top_ins_district_cols = {
    'Year': [],
    'Quarter': [],
    'District': [],
    'Metric_Type': [],
    'Transaction_Count': [],
    'Transaction_Amount': []
}

top_ins_pincode_cols = {
    'Year': [],
    'Quarter': [],
    'Pincode': [],
    'Metric_Type': [],
    'Transaction_Count': [],
    'Transaction_Amount': []
}

# Loop through year folders
year_list = os.listdir(top_ins__path)

for year in year_list:
    year_path = os.path.join(top_ins__path, year)
    if not os.path.isdir(year_path):
        continue

    # Loop through quarter json files inside the year folder
    quarter_files = os.listdir(year_path)

    for q_file in quarter_files:
        if not q_file.endswith('.json'):
            continue

        q_path = os.path.join(year_path, q_file)
        quarter = int(q_file.strip('.json'))  # '1.json' -> 1

        with open(q_path, 'r', encoding='utf-8') as f:
            D = json.load(f)

        # -------------------- STATES --------------------
        states_list = D['data'].get('states')
        if states_list:
            for s in states_list:
                top_ins_state_cols['Year'].append(year)
                top_ins_state_cols['Quarter'].append(quarter)
                top_ins_state_cols['State'].append(s['entityName'])
                top_ins_state_cols['Metric_Type'].append(s['metric']['type'])
                top_ins_state_cols['Transaction_Count'].append(s['metric']['count'])
                top_ins_state_cols['Transaction_Amount'].append(s['metric']['amount'])

        # -------------------- DISTRICTS --------------------
        districts_list = D['data'].get('districts')
        if districts_list:
            for d in districts_list:
                top_ins_district_cols['Year'].append(year)
                top_ins_district_cols['Quarter'].append(quarter)
                top_ins_district_cols['District'].append(d['entityName'])
                top_ins_district_cols['Metric_Type'].append(d['metric']['type'])
                top_ins_district_cols['Transaction_Count'].append(d['metric']['count'])
                top_ins_district_cols['Transaction_Amount'].append(d['metric']['amount'])

        # -------------------- PINCODES --------------------
        pincodes_list = D['data'].get('pincodes')
        if pincodes_list:
            for p in pincodes_list:
                top_ins_pincode_cols['Year'].append(year)
                top_ins_pincode_cols['Quarter'].append(quarter)
                top_ins_pincode_cols['Pincode'].append(p['entityName'])
                top_ins_pincode_cols['Metric_Type'].append(p['metric']['type'])
                top_ins_pincode_cols['Transaction_Count'].append(p['metric']['count'])
                top_ins_pincode_cols['Transaction_Amount'].append(p['metric']['amount'])

# Create DataFrames
top_ins__state_df = pd.DataFrame(top_ins_state_cols)
top_ins__district_df = pd.DataFrame(top_ins_district_cols)
top_ins__pincode_df = pd.DataFrame(top_ins_pincode_cols)

In [27]:
top_ins__state_df

,Year,Quarter,State,Metric_Type,Transaction_Count,Transaction_Amount
0,2020,2,maharashtra,TOTAL,39836,6879717.0
1,2020,2,karnataka,TOTAL,27358,4794150.0
2,2020,2,andhra pradesh,TOTAL,22104,3982391.0
3,2020,2,telangana,TOTAL,19003,3419453.0
4,2020,2,delhi,TOTAL,11716,1897480.0
...,...,...,...,...,...,...
185,2024,4,kerala,TOTAL,89533,144083113.0
186,2024,4,telangana,TOTAL,78498,124755619.0
187,2024,4,rajasthan,TOTAL,73530,127930986.0
188,2024,4,delhi,TOTAL,67962,94390728.0
189,2024,4,bihar,TOTAL,62662,83739800.0

In [28]:
import sqlalchemy as sa
import pyodbc
import pandas as pd

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=VIGNESH\\SQLEXPRESS;"
    "DATABASE=phonepe;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()
print("Connected to SQL Server!")
# Connection string for MSSQL
conn_str = (
    "mssql+pyodbc://VIGNESH\\SQLEXPRESS/phonepe?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

engine= create_engine(conn_str)

# Insert state dataframe
top_ins__state_df.to_sql(
    "top_ins_state",
    con=engine
    ,
    if_exists="append",
    index=False
)

# Insert district dataframe
top_ins__district_df.to_sql(
    "top_ins_district",
    con=engine
    ,
    if_exists="append",
    index=False
)

# Insert pincode dataframe
top_ins__pincode_df.to_sql(
    "top_ins_pincode",
    con=engine
    ,
    if_exists="append",
    index=False
)

print("All 3 dataframes inserted successfully!")

Connected to SQL Server!

All 3 dataframes inserted successfully!